### ISSUE TITLE
Private posts

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-handbook-theme#11]
We want to have private pages on the site that are only accessible to logged in users.

This should be indicated visually on the page. Maybe an icon or a red bar or something.

**Comment by sambulance** [comment]
I think this should be the other way round - put emphasis on stuff that will be made public. I think this is especially important when editing a post that is already live and public, as the person editing might not be aware. Perhaps we could have a two-step publishing process for public posts? eg. alert box when publish is clicked "This content is public, are you sure you want to publish? Yes / No".

**Comment by mattheu** [comment]
Interesting idea. We did a 'are you sure' pop up for a client once - and I kinda quite liked. 

That said - I think the plan is for MOST content to be public, so perhaps we'll get more used to it.

However, I still like the idea of an icon or something. On the front end right now, WP prepends the word 'private' to the title of a private page, which i'm not so keen on. Especially if you're scanning through the nav or something.

**Comment by rmccue** [comment]
These should be indicated in the menu too, probably with a 🔒 icon. Right now, hard to tell which pages are private.

**Comment by mattheu** [comment]
https://github.com/humanmade/hm-handbook-theme/pull/50

**Comment by mattheu** [comment]
Done. We have icons in the menu, and emoji in the title
