### ISSUE TITLE
Automatically list child pages at the top of the page

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-handbook-theme#18]
The current handbook theme automatically lists child pages at the top of the page.

Would love to hear your thoughts on this.

- Do we still want this?
- Are we happy having it so prominent at the top?
- Should the main sidebar replace this?

Maybe @smckeown / @anafransilva or others from the content side have some thoughts?

**Comment by anafransilva** [comment]
I quite like the idea, and it makes sense to me to have pages within the same 'family' visible on the page you're reading. For someone unfamiliar with the handbook having 'Your First Week' listed prominently at the top of 'Your First Day' seems like a nice way to direct people to the following page. 

On the other hand, from a navigational point of view the sidebar seems like a better option if you want to just move around different pages/categories of information; but I don't necessarily think it should replace it. Would it be unreasonable to have both?

**Comment by mattheu** [comment]
My only real concern with having it above the content is that it pushes the actual content quite far down the page. 

If the sidebar has all the content and it is properly organized, there probably isn't any need for both. However if the sidebar just includes some higher level stuff then maybe it would be useful. Perhaps in some kind of box that is aligned to the right?

**Comment by mattheu** [comment]
I think thats what I wanted to hear! Going to close the ticket. Just want to make sure we catch all the current functionality!
