### ISSUE TITLE
Subtitle below logo 

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-handbook-theme#23]
Currently it just shows the logo in the header, but potentially we'll be using this on several sites - so would be good to display the title below this. Or something similar.

Something like this

![image](https://cloud.githubusercontent.com/assets/494927/16733454/8b8a12fc-4779-11e6-8219-6e8a700d9251.png)

**Comment by noeltock** [comment]
This looks good 👍  Two opinions on the logo:
- Could probably be smaller
- More whitespace around the logo to isolate it some more

**Comment by mattheu** [comment]
Done
