### ISSUE TITLE
Home URL inconsistencies

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-handbook-theme#26]
This is _very_ minor, but just wanted to flag that we are putting slashes in different places when using `home_url()`:

https://github.com/humanmade/hm-handbook-theme/blob/master/searchform.php#L2
`action="<?php echo esc_url( home_url( '/' ) ); ?>"`

https://github.com/humanmade/hm-handbook-theme/blob/master/header.php#L33
`href="<?php echo esc_url( home_url() ); ?>/"`

Probably best to go with the searchform version?

**Comment by mattheu** [comment]
👍  Actually I think for the home page, it redirects to unslashed, and all other pages it will ensure the slash. So I think here we can remove from searchform.

**Comment by mattheu** [comment]
Just pushed this straight to master as its so tiny.
