### ISSUE TITLE
Make pages private by default?

### ISSUE THREAD

**Issue by johnbillion** [humanmade/hm-handbook-theme#59]
Related: #11

While the handbook is not yet public, I think pages published on the handbook should be private by default, to avoid unintentionally publicly publishing content that contains sensitive information when the handbook does go public.

This can be as simple as setting the `post_status` to `private` when first writing a page:

``` php
add_filter( 'wp_insert_post_data', function( array $post_data ) {
    if ( 'page' == $post_data['post_type'] && 'auto-draft' === $post_data['post_status'] ) {
        $post_data['post_status'] = 'private';
    }
    return $post_data;
} );
```

**Comment by mattheu** [comment]
👍

**Comment by willmot** [comment]
Agreed 👍

**Comment by smckeown** [comment]
+1

**Comment by mattheu** [comment]
This might be a good one to get in for launch?

**Comment by sambulance** [comment]
Started looking at this the other day, tried the function @johnbillion provided, but it causes an auto-draft to publish privately immediately rather than when publish is hit.

I tried hooking into some of the post status transition hooks to change the status to private when going from draft or auto-draft to publish, but it doesn't look like you can use these to change the post data. 

Googling suggests we use a bit of JS to select private in the admin rather than trying to change the post data. Any other ideas?

/cc @mattheu @johnbillion

**Comment by mattheu** [comment]
Tricky one this. The way we have set this theme up, 'private' really means published internally. This is OK in terms of not leaking data, but means incomplete content is getting published on the site.

 What we want is a 'private draft', but there is no such thing in WordPress. The statuses are 'auto-draft', 'draft', 'publish', 'private'. 

So the the code John suggested is probably the closest we can get to this goal, if its simply about leaking data, but makes the experience feel a bit buggy and unexpected, plus we may end up with unfinished/unapproved content published to the site.

I can think of a couple of ways around this.
- Have a meta field/checkbox that states 'this post is approved and ready to be published'. You can then check the value of this on a post status transition action, and only publish if checked. I think we did something similar on Newton.
- Try and implement a custom status of 'private-draft', but this feels hard.

**Comment by mattheu** [comment]
Since this isn't quite as simple as first thought, i'm going to remove this from the 'next' milestone. I don't think it needs to be a blocker to launching this site publicly.

**Comment by mattheu** [comment]
I think this issue is probably a better solution to this problem: https://github.com/humanmade/hm-handbook-theme/issues/67

**Comment by willmot** [comment]
@mattheu agreed, I’m going to close this in favour of #67
