### ISSUE TITLE
Front page

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-handbook-theme#6]
The front page of the pattern library will need some unique design.
- some kind of intro about what this is. Especially important as its going to be made public.
- lists of info. eg new/recently updated. Comments. something similar to what we've got now but a bit more useful.

Anything else we can thing of?

**Comment by sambulance** [comment]
I've been working on an updates section at the bottom of the homepage:

![screencapture-handbook-dev-1478890658554](https://cloud.githubusercontent.com/assets/5014023/20226804/7b724dfc-a841-11e6-9a8f-6f51ede6cce3.png)

Similar to the old handbook, but with a bit of extra info about how recent the updates are. The edited section only shows three on mine but will have max five, I've only got three edited posts on my local copy.

It's still a work in progress, but would love some feedback please :)

**Comment by tareiking** [comment]
@sambulance - looks great! Can users link through to a larger list of recent edits / latest pages from the widget?

Not sure if that is a useful suggestion - as I think there are only 2 times in my entire history I've ever wanted to know more 'recent news' on websites, but I am a little more interested in the HM content than the rest of the web.

**Comment by mattheu** [comment]
Love it. I was thinking we needed exactly this. 

+1 on Tarei's comment regarding linking through to a new archive page listing recent edits,  can maybe be tackled separately.

**Comment by sambulance** [comment]
Great idea. I find myself wanting the same in the Hub. Perhaps we can split into a new ticket to look at in future?

PR for this: https://github.com/humanmade/hm-handbook-theme/pull/76

**Comment by sambulance** [comment]
Closing this now, any more suggestions for homepage improvements can be new tickets :)

New tickets for updates archives: https://github.com/humanmade/hm-handbook-theme/issues/81
