### ISSUE TITLE
Disable autocomplete in the ajax search bar

### ISSUE THREAD

**Issue by johnbillion** [humanmade/hm-handbook-theme#65]
The search bar shows the browser's autocomplete results over the top of the AJAX search results. It should be disabled with:

`autocomplete="off"`

<img width="855" alt="screen shot 2016-10-10 at 12 13 39" src="https://cloud.githubusercontent.com/assets/208434/19234374/1bc56c1c-8ee3-11e6-81ec-68c31e5e4dd9.png">

**Comment by mattheu** [comment]
👍

**Comment by sambulance** [comment]
Fix for this in https://github.com/humanmade/hm-handbook-theme/pull/79
