### ISSUE TITLE
Create button so that employees can acknowledge they have read policies/hb info

### ISSUE THREAD

**Issue by smckeown** [humanmade/hm-handbook-theme#66]
The HR company we are working with have recommended that we should have some sort of record of when employees have read and understood HR policies and documents. We should be able to achieve this in WordPress. On each HR-related page there could be a button that an employee can click to acknowledge that they have read and understood a page (it wouldn't be necessary on pages like client project pages, events, etc).

The flow would be as follows:

v1

**Frontend**

1. User goes to page
2. User reads page
3. User clicks button to acknowledge they have read and understood page
4. A list of avatars shows who has clicked and who hasn't (like we have on our updates posts)

**backend**
1. Author creates page
2. Author clicks checkbox that says "Required Reading" (using a custom field)
3. Below post, author can see avatars of who has read and who hasn't.

v2

*frontend**
1. When user goes to handbook, they are shown a list of pages they have to confirm they have read (not sure where or how that would fit into the design).

**Comment by mattheu** [comment]
How would this be affected by changes to the content? 

Idea - the author can 'reset' the state on that post if they have made significant changes, but otherwise are allowed to make small edits without clearing this?

**Comment by smckeown** [comment]
Good idea. The author should manually reset it if there has been a major change. It would be nice to also display what that major change is so people a) know exactly what's changed, and b) don't have to read the whole thing again.

**Comment by Japh** [comment]
Interesting. Did the HR company say how this sort of thing works in companies where the policies are all in standard Office documents? How do they record the information, and what do they do when changes are made?

**Comment by smckeown** [comment]
Good question @Japh - they didn't say but I will ask.

**Comment by smckeown** [comment]
Just want to re-address this. I chatted to the HR consultant and he said that people do this is many different ways, from signing something to sending an email to acknowledge.

From our perspective it would be easiest to have something that people can just click, that way all of the data is just stored in the handbook.

It would be useful, though, to do it slightly differently:

1. Have a button that people can click to acknowledge that they have read the entire handbook (rather than on individual pages).
2. For important updates, people will need to acknowledge that they have read them. We could do it so the author can click a box that says "major change" and then the team is emailed with that change. Ideally they could acknowledge they have read it from the site, or just respond to the email to acknowledge it.

**Comment by joehoyle** [comment]
Is this an hr thing for liability, or is it so people can track themselves what they have read?

If it's the latter, I'm not sure we need a system for that - or rather I'm not sure what is special about the handbook as opposed to any other information we update that would require such a special use case. Adding a comment here as I reminder for me to read up on this as more as anything else :)

**Comment by smckeown** [comment]
It's a hr thing for liability.

**Comment by mattheu** [comment]
Just a note that this is done.

@smckeown You discussed having this enabled only on a single page that says something like - I have read the whole handbook. Is this correct, rather than having it on a per-page basis. Do you need me to set this up for you?

**Comment by smckeown** [comment]
The plugin is causing a "Are you sure you want to do this?" message when I try to add a new page.

Screenshot:
![error message](https://www.dropbox.com/s/evy6nghnu948yfz/Screenshot%202017-05-23%2008.04.01.png?raw=1)

I deactivated the plugin and was able to add a new page no problem. When I reactivated it, it was broken again.

**Comment by willmot** [comment]
This is now active and working on the handbook.
