### ISSUE TITLE
Add disclaimer to footer

### ISSUE THREAD

**Issue by smckeown** [humanmade/hm-handbook-theme#69]
The following text should be added to the footer of all handbook pages:

> This handbook is a document of how we do things at Human Made. You are free to use it but we cannot guarantee it is fit for your purpose. You should always enlist a HR consultant to ensure you meet your legal requirements.

**Comment by mattheu** [comment]
@sambulance I wonder if we should have something like a wiget area in the footer to manage stuff like this?

**Comment by sambulance** [comment]
@mattheu Yeah it would be good to have this to be editable in the customiser too

**Comment by sambulance** [comment]
PR: https://github.com/humanmade/hm-handbook-theme/pull/82

Added a widget area to the footer, so a text widget can be added. Tweaked the styling a little but open to suggestions. Made it the same width as the content area.

![screencapture-handbook-dev-1479476890934](https://cloud.githubusercontent.com/assets/5014023/20432154/c35d48f2-ad95-11e6-8c42-17e4f9ab67d7.png)

**Comment by willmot** [comment]
This is now live on the site.
