### ISSUE TITLE
Pre-launch

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-handbook-theme#70]
Catch all ticket for all those small things we should do before making this thing public.

- [x] Testing. 
- [x] Cross browser testing. 
- [x] Mobile testing
- [x] Optimisation

**Comment by sambulance** [comment]
Found a bug in the pattern library that needs merging before launch. PR here: https://github.com/humanmade/hm-pattern-library/pull/93

**Comment by mattheu** [comment]
Fixed. I'll update the version of the pattern library in use by this theme.

**Comment by sambulance** [comment]
@mattheu I think I've got one or two more fixes in the pattern library first, sorry.

If there's docs on how to update this version, I could do it when I'm done? I noticed it's the same branch as `gh-pages`? Is it just a manual push to that branch?

**Comment by mattheu** [comment]
OK cool - I've not done it yet :)

You need to do a release on the hm-pattern-library. To do this you compile the project locally, and update the gh-pages branch with the contents of the dist directory. Its a little complex - maybe best I'll do it. I've been meaning to write a script to do this for you!

**Comment by sambulance** [comment]
@mattheu Done browser testing now, there's just one more PR on the pattern library then we can release and update the refs here. I might try and get it working :)

Here's the PR for the browser fixes done within the handbook: https://github.com/humanmade/hm-handbook-theme/pull/79

Did you have anything specific in mind for the optimising? I can see the JS isn't minified, can fix that, but the CSS is. The SVGs are optimised through the pattern library. Anything else?

**Comment by mattheu** [comment]
JS - yeah I'm pretty sure we can just tell webpack to build minified JS.

Anything else - nothing specific really, just take a look over see if there are any glaring issues.

**Comment by sambulance** [comment]
I'd say this is all done now :)
