### ISSUE TITLE
A way for people to suggest missing content

### ISSUE THREAD

**Issue by willmot** [humanmade/hm-handbook-theme#94]
Ideally we’d have a simple way for people to suggest missing content or content that they’d like to see included. Perhaps a form of some kind or a link to a P2 maybe?

**Comment by richardswain** [comment]
@willmot If the suggestions are only from humans then maybe a 'Handbook' category post on the Wild Ideas P2 would be sufficient? Alternatively, there is the #company-handbook Slack channel available for discussion. We could create a private page with suitable content on the handbook site to link to the P2.

**Comment by willmot** [comment]
Yeah I agree both wild ideas and the handbook channel probably cover this so I think we can close. It'll also be superseded by the playbook I think.
